version: '1.0'

services:
  profile:
    build: ./
    container_name: 'mission-profile'
    networks:
      - mission-gateway_mission
      - mission-db_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mission_db
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_AUTH_DATABASE: admin
networks:
  mission-db_mongo:
    external: true
  mission-gateway_mission:
    external: true