version: '1.0'

services:
  mongo:
    image: mongo:6.0.3
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: profile_db
    volumes:
      - ./assets/db_data/mongo/db:/data/db
      - ./assets/db_data/mongo/configdb:/data/configdb
    networks:
      - profile_back
  profile:
    build: ./
    container_name: 'mission-profile'
    networks:
      - mission-gateway_mission
      - profile_back
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: profile_db
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_AUTH_DATABASE: admin
networks:
  profile_back:
    driver: bridge
    name: profile_back
  mission-gateway_mission:
    external: true